/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './App.tsx',
    './auth.tsx',
    './index.tsx',
    './components/**/*.{ts,tsx}',
    './features/**/*.{ts,tsx}',
    './config/**/*.{ts,tsx}',
    './utils/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
    './types.ts',
    './constants.ts',
  ],
  darkMode: 'class',
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      white: 'rgb(var(--brand-white-rgb) / <alpha-value>)',
      black: 'rgb(var(--brand-text-rgb) / <alpha-value>)',
      primary: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
      surface2: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
      'muted-fg': 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
      slate: {
        50: 'rgb(var(--brand-neutral-50-rgb) / <alpha-value>)',
        100: 'rgb(var(--brand-neutral-100-rgb) / <alpha-value>)',
        200: 'rgb(var(--brand-neutral-200-rgb) / <alpha-value>)',
        300: 'rgb(var(--brand-neutral-300-rgb) / <alpha-value>)',
        400: 'rgb(var(--brand-neutral-400-rgb) / <alpha-value>)',
        500: 'rgb(var(--brand-neutral-500-rgb) / <alpha-value>)',
        600: 'rgb(var(--brand-neutral-600-rgb) / <alpha-value>)',
        700: 'rgb(var(--brand-neutral-700-rgb) / <alpha-value>)',
        800: 'rgb(var(--brand-neutral-800-rgb) / <alpha-value>)',
        900: 'rgb(var(--brand-neutral-900-rgb) / <alpha-value>)',
        950: 'rgb(var(--brand-neutral-950-rgb) / <alpha-value>)',
      },
      gray: {
        50: 'rgb(var(--brand-neutral-50-rgb) / <alpha-value>)',
        100: 'rgb(var(--brand-neutral-100-rgb) / <alpha-value>)',
        200: 'rgb(var(--brand-neutral-200-rgb) / <alpha-value>)',
        300: 'rgb(var(--brand-neutral-300-rgb) / <alpha-value>)',
        400: 'rgb(var(--brand-neutral-400-rgb) / <alpha-value>)',
        500: 'rgb(var(--brand-neutral-500-rgb) / <alpha-value>)',
        600: 'rgb(var(--brand-neutral-600-rgb) / <alpha-value>)',
        700: 'rgb(var(--brand-neutral-700-rgb) / <alpha-value>)',
        800: 'rgb(var(--brand-neutral-800-rgb) / <alpha-value>)',
        900: 'rgb(var(--brand-neutral-900-rgb) / <alpha-value>)',
        950: 'rgb(var(--brand-neutral-950-rgb) / <alpha-value>)',
      },
      blue: {
        50: 'rgb(var(--brand-surface-rgb) / <alpha-value>)',
        100: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        200: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        300: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        400: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        500: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        600: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        700: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        800: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        900: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        950: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
      },
      sky: {
        50: 'rgb(var(--brand-surface-rgb) / <alpha-value>)',
        100: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        200: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        300: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        400: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        500: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        600: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        700: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        800: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        900: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        950: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
      },
      cyan: {
        50: 'rgb(var(--brand-surface-rgb) / <alpha-value>)',
        100: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        400: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        500: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        600: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
      },
      emerald: {
        50: 'rgb(var(--brand-surface-rgb) / <alpha-value>)',
        100: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        200: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        300: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        400: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        500: 'rgb(var(--brand-primary-bright-rgb) / <alpha-value>)',
        600: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        700: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        800: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        900: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        950: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
      },
      green: {
        50: 'rgb(var(--brand-surface-rgb) / <alpha-value>)',
        100: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        300: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        400: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        500: 'rgb(var(--brand-primary-bright-rgb) / <alpha-value>)',
        600: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        700: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        800: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        900: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
      },
      teal: {
        50: 'rgb(var(--brand-surface-rgb) / <alpha-value>)',
        400: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        500: 'rgb(var(--brand-primary-bright-rgb) / <alpha-value>)',
        950: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
      },
      amber: {
        50: 'rgb(var(--brand-surface-rgb) / <alpha-value>)',
        100: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        200: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        300: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        400: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        500: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        600: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        700: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        800: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        900: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        950: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
      },
      yellow: {
        100: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        300: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        700: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        900: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
      },
      rose: {
        50: 'rgb(var(--brand-surface-rgb) / <alpha-value>)',
        100: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        200: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        300: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        400: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        500: 'rgb(var(--brand-primary-bright-rgb) / <alpha-value>)',
        600: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        700: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        800: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        900: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        950: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
      },
      red: {
        50: 'rgb(var(--brand-surface-rgb) / <alpha-value>)',
        100: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        200: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        300: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        400: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        500: 'rgb(var(--brand-primary-bright-rgb) / <alpha-value>)',
        600: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        700: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        800: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        900: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        950: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
      },
      pink: {
        100: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        300: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        400: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        500: 'rgb(var(--brand-primary-bright-rgb) / <alpha-value>)',
        600: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        700: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        800: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        900: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
      },
      lime: {
        50: 'rgb(var(--brand-surface-rgb) / <alpha-value>)',
        100: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        200: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        300: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        400: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        500: 'rgb(var(--brand-primary-bright-rgb) / <alpha-value>)',
        600: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        700: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        800: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        900: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        950: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
      },
      violet: {
        50: 'rgb(var(--brand-surface-rgb) / <alpha-value>)',
        100: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        200: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        300: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        400: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        500: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        600: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        700: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        800: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        900: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        950: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
      },
      purple: {
        50: 'rgb(var(--brand-surface-rgb) / <alpha-value>)',
        100: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        200: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        300: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        400: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        500: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        600: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        700: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        800: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        900: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        950: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
      },
      orange: {
        400: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        600: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
      },
      indigo: {
        100: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        200: 'rgb(var(--brand-accent-surface-rgb) / <alpha-value>)',
        300: 'rgb(var(--brand-accent-rgb) / <alpha-value>)',
        700: 'rgb(var(--brand-primary-rgb) / <alpha-value>)',
        800: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
        900: 'rgb(var(--brand-primary-deep-rgb) / <alpha-value>)',
      },
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
